export const baseEnv = {
  production: false,
  apiUrl: 'https://localhost:7103/api',
  //apiUrl: 'api',
  apiUrlshorten: 'https://localhost:7103',
  query: 'query',
  command: 'command',
  articles: 'articles',
  exercises: 'breath-exercises',
  categories: 'categories',
  authentication: 'authentication',
  registration: 'registration',
  users: 'users',
}

export const environment = {
  deleteCookieUrl: `${baseEnv.apiUrl}/${baseEnv.authentication}/delete-cookie`,
  invalidateTokensUrl: `${baseEnv.apiUrl}/${baseEnv.authentication}/invalidate-tokens`,
  forgetPasswordUrl: `${baseEnv.apiUrl}/${baseEnv.authentication}/forgot-password`,
  forgetPasswordresponseUrl: `${baseEnv.apiUrl}/${baseEnv.authentication}/forgot-password-response`,
  loginUrl: `${baseEnv.apiUrl}/${baseEnv.authentication}/authenticate`,
  logoutUrl: `${baseEnv.apiUrl}/${baseEnv.authentication}/logout`,
  resetPasswordUrl: `${baseEnv.apiUrl}/${baseEnv.authentication}/reset-password`,
  resetForgottenPasswordUrl: `${baseEnv.apiUrl}/${baseEnv.authentication}/reset-forgotten-password`,
  refreshAccessTokenUrl: `${baseEnv.apiUrl}/${baseEnv.authentication}/refresh-access-token`,
  verifyEmailUrl: `${baseEnv.apiUrl}/${baseEnv.authentication}/verify-email`,
  resendEmailVerificationUrl: `${baseEnv.apiUrl}/${baseEnv.authentication}/resend-verify-email`,

  registrationUrl: `${baseEnv.apiUrl}/${baseEnv.registration}/register`,

  articleSearchUrl: `${baseEnv.apiUrl}/${baseEnv.articles}/${baseEnv.query}/search`,
  articleIndexUrl: `${baseEnv.apiUrl}/${baseEnv.articles}/${baseEnv.query}/index`,
  articleGetLastUrl: `${baseEnv.apiUrl}/${baseEnv.articles}/${baseEnv.query}/index-last`,
  articleGetByCategoryUrl: `${baseEnv.apiUrl}/${baseEnv.articles}/${baseEnv.query}/index-by-category`,
  articleCreateUrl: `${baseEnv.apiUrl}/${baseEnv.articles}/${baseEnv.command}/create`,
  articleQueryUrl: `${baseEnv.apiUrl}/${baseEnv.articles}/${baseEnv.query}`,
  articleCommandUrl: `${baseEnv.apiUrl}/${baseEnv.articles}/${baseEnv.command}`,
  imageUploadUrl: `${baseEnv.apiUrl}/${baseEnv.articles}/${baseEnv.command}/upload-image`,
  imageDisplayUrl: `${baseEnv.apiUrlshorten}`,

  categoryIndexUrl: `${baseEnv.apiUrl}/${baseEnv.categories}/${baseEnv.query}/index`,
  categoryCreateUrl: `${baseEnv.apiUrl}/${baseEnv.categories}/${baseEnv.command}/create`,
  categorysQueryUrl: `${baseEnv.apiUrl}/${baseEnv.categories}/${baseEnv.query}`,
  categoryCommandUrl: `${baseEnv.apiUrl}/${baseEnv.categories}/${baseEnv.command}`,

  exerciseIndexUrl: `${baseEnv.apiUrl}/${baseEnv.exercises}/${baseEnv.query}/index`,
  exerciseCreateUrl: `${baseEnv.apiUrl}/${baseEnv.exercises}/${baseEnv.command}/create`,
  exercisesQueryUrl: `${baseEnv.apiUrl}/${baseEnv.exercises}/${baseEnv.query}`,
  exerciseCommandUrl: `${baseEnv.apiUrl}/${baseEnv.exercises}/${baseEnv.command}`,

  userSearchUrl: `${baseEnv.apiUrl}/${baseEnv.users}/${baseEnv.query}/search`,
  userIndexUrl: `${baseEnv.apiUrl}/${baseEnv.users}/${baseEnv.query}/index`,
  userGetbyUsernameUrl: `${baseEnv.apiUrl}/${baseEnv.users}/${baseEnv.query}/details`,
  userGetProfileUrl: `${baseEnv.apiUrl}/${baseEnv.users}/${baseEnv.query}/profile`,
  userGetMinimumProfileUrl: `${baseEnv.apiUrl}/${baseEnv.users}/${baseEnv.query}/minimum-profile`,
  accountActivationUrl: `${baseEnv.apiUrl}/${baseEnv.users}/${baseEnv.command}/account-activation`,
  userQueryUrl: `${baseEnv.apiUrl}/${baseEnv.users}/${baseEnv.query}`,
  userCommandUrl: `${baseEnv.apiUrl}/${baseEnv.users}/${baseEnv.command}`,
 }
